### ISSUE TITLE
Run Cli with pytest and get error

### ISSUE THREAD

**Issue by nba2023** [DetachHead/pytest-robotframework#252]
OS: window WSL2
python version: 3.10.6
pytest version: 7.4.0
robot related: 
robotframework                 7.0
robotframework-httplibrary     0.4.2
robotframework-pythonlibcore   2.2.1
robotframework-requests        0.7.1
robotframework-scplibrary      1.2.0
robotframework-sshlibrary      3.8.0
robotframework-websocketclient 1.3.0
robotframework-xvfb            1.2.2

After install 
`python -m pip install pytest_robotframework`
(...)
Successfully installed ansi2html-1.9.1 basedtyping-0.1.3 pytest_robotframework-4.1.1

`pytest --version`
```
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 1075, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 1305, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/home/ahua/.local/lib/python3.10/site-packages/pytest_robotframework/_internal/pytest/plugin.py", line 16, in <module>
    from pluggy import Result
ImportError: cannot import name 'Result' from 'pluggy' (/usr/local/lib/python3.10/dist-packages/pluggy/__init__.py)
```
How to resolve this issue? 
Thanks for help.

**Comment by DetachHead** [comment]
i guess you have a different version of pluggy (one of pytest's dependencies) installed which doesn't export the `Result` class. it looks like that import was only used for type checking old `hookwrapper` functions anyway, so i got rid of it by updating them to use [new wrappers](https://pluggy.readthedocs.io/en/stable/index.html#wrappers) instead.

can you see if #253 fixes the issue?

```
pip install git+https://github.com/DetachHead/pytest-robotframework@switch-to-new-hook-wrappers
```

**Comment by nba2023** [comment]
I follow your command and got another error:

```
# pip uninstall pytest_robotframework
WARNING: Skipping pytest_robotframework as it is not installed.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

# python -m pip install --upgrade pip --proxy=$my_proxy
Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (23.3.1)
Collecting pip
  Using cached pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.3.1
    Uninstalling pip-23.3.1:
      Successfully uninstalled pip-23.3.1
Successfully installed pip-24.0

# python -m pip install git+https://github.com/DetachHead/pytest-robotframework@switch-to-new-hook-wrappers --proxy=$my_proxy
Collecting git+https://github.com/DetachHead/pytest-robotframework@switch-to-new-hook-wrappers
  Cloning https://github.com/DetachHead/pytest-robotframework (to revision switch-to-new-hook-wrappers) to /tmp/pip-req-build-kgepgxax
  Running command git clone --filter=blob:none --quiet https://github.com/DetachHead/pytest-robotframework /tmp/pip-req-build-kgepgxax
  fatal: unable to access 'https://github.com/DetachHead/pytest-robotframework/': gnutls_handshake() failed: Error in the pull function.
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/DetachHead/pytest-robotframework /tmp/pip-req-build-kgepgxax did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/DetachHead/pytest-robotframework /tmp/pip-req-build-kgepgxax did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by DetachHead** [comment]
see if the latest release (4.1.2) fixes your issue

**Comment by nba2023** [comment]
I install `pytest_robotframework`  again but when type `pytest -V`
The erro is as follows:
```
# python -m pip install pytest_robotframework --proxy=$my_proxy
<...>
Installing collected packages: robotframework, basedtyping, ansi2html, pytest_robotframework
  Attempting uninstall: robotframework
    Found existing installation: robotframework 6.0
    Uninstalling robotframework-6.0:
      Successfully uninstalled robotframework-6.0
Successfully installed ansi2html-1.9.1 basedtyping-0.1.3 pytest_robotframework-4.1.2 robotframework-7.0

# pytest -V
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 1075, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 1305, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/usr/local/lib/python3.10/dist-packages/pytest_robotframework/_internal/pytest/plugin.py", line 60, in <module>
    from pytest_robotframework._internal.robot.listeners_and_suite_visitors import (
  File "/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/usr/local/lib/python3.10/dist-packages/pytest_robotframework/_internal/robot/listeners_and_suite_visitors.py", line 26, in <module>
    from pluggy import HookCaller, HookImpl
ImportError: cannot import name 'HookCaller' from 'pluggy' (/usr/local/lib/python3.10/dist-packages/pluggy/__init__.py)
```
After remove pluggy and reinstall it, the `pytest -V` do worked
Thanks a lot for help.
